version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: tsdb_financedata
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - tsdbdata:/var/lib/postgresql/data

volumes:
  tsdbdata:
