version: "3.10"
services:
  timescaledb:
    image: docker.io/timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_USER: tsuser
      POSTGRES_PASSWORD: ts_password
      POSTGRES_DB: time_series_raw
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./k8s/timescaledb-init:/docker-entrypoint-initdb.d

volumes:
  timescaledb-data: